Written by 김천지

## 상위 150개의 카테고리에 해당하지 않는 데이터는 제거한다.

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns
import os

# get the file path
file_path = os.getcwd() + '/cleaned_quotes_001.csv'

# read the file
df = pd.read_csv(file_path)

In [88]:
# drop nan values
df = df.dropna()

In [90]:
df

,quote,author,category,token length,author_name_only
0,"I'm selfish, impatient and a little insecure. ...",Marilyn Monroe,"best, life, love, mistakes, truth",41,marilyn monroe
1,You know you're in love when you can't fall as...,Dr. Seuss,"dreams, love, reality, sleep",18,dr. seuss
2,A friend is someone who knows all about you an...,Elbert Hubbard,"friend, friendship, knowledge, love",13,elbert hubbard
3,Darkness cannot drive out darkness: only light...,"Martin Luther King Jr., A Testament of Hope: T...","darkness, drive-out, hate, inspirational, light",20,martin luther king jr.
4,We accept the love we think we deserve.,"Stephen Chbosky, The Perks of Being a Wallflower","inspirational, love",8,stephen chbosky
...,...,...,...,...,...
183655,Stephen King in many respects is a wonderful w...,Anne Rice,"reading, people, king",39,anne rice
183656,One faces the future with one's past.,Pearl S. Buck,"past, faces",7,pearl s. buck
183657,What else does anxiety about the future bring ...,Thomas a Kempis,"anxiety, you, sorrow",13,thomas a kempis
183658,The wave of the future is coming and there is ...,Anne Morrow Lindbergh,"fighting, wave, coming",13,anne morrow lindbergh
183659,The fact is that all writers create their prec...,Jorge Luis Borges,"work, past, create",26,jorge luis borges

In [91]:
category_candidates = [
 'sadness',
 'quote',
 'freedom',
 'poetry',
 'time',
 'imagination',
 'fantasy',
 'religion',
 'pain',
 'psychology',
 'prayer',
 'wisdom',
 'power',
 'romance',
 'writers',
 'mind',
 'self-help',
 'trust',
 'passion',
 'relationships',
 'purpose',
 'books',
 'humor',
 'truth',
 'dreams',
 'children',
 'beauty',
 'travel',
 'kindness',
 'living',
 'joy',
 'education',
 'thoughts',
 'courage',
 'politics',
 'success',
 'intelligence',
 'inspiring',
 'calling',
 'growth',
 'belief',
 'loss',
 'leadership',
 'great',
 'spiritual',
 'future',
 'funny',
 'motivational',
 'confidence',
 'positive-thinking',
 'happiness',
 'sex',
 'hope',
 'peace',
 'positive',
 'creativity',
 'philosophy',
 'faith',
 'quotes',
 'forgiveness',
 'war',
 'self',
 'people',
 'action',
 'reality',
 'love',
 'god',
 'me',
 'inspirational',
 'literature',
 'inspiration',
 'strength',
 'wealth',
 'friends',
 'money',
 'spirituality',
 'fear',
 'failure',
 'marriage',
 'past',
 'humanity',
 'good',
 'words',
 'reading',
 'you',
 'destiny',
 'humour',
 'change',
 'art',
 'christian',
 'writing',
 'relationship',
 'dream',
 'society',
 'think',
 'depression',
 'motivation',
 'learning',
 'knowledge',
 'life',
 'advice',
 'nature',
 'science',
 'world',
 'fiction',
 'family',
 'soul',
 'light',
 'goals',
 'magic',
 'death',
 'music',
 'history',
 'man',
 'business',
 'friendship',
 'work'
]

In [ ]:
# 상위 150개의 카테고리가 category_candidates에 있다.
# 아래 함수는 각 데이터의 카테고리가 category_candidates에 있는지 확인하는 함수이다.
# 이 함수가 1을 반환하면 상위 150개의 카테고리가 포함되어 있다는 뜻이다.
# 이 함수가 0을 반환하면 상위 150개의 카테고리가 포함되어 있지 않다는 뜻이다.
def is_in_candidates(category):
    # print(category)
    each_category = category.split(',')
    for each in each_category:
        if each.strip() in category_candidates:
            return 1
    return 0

In [ ]:
# in_candidates 컬럼을 추가하여 각 데이터가 상위 150개의 카테고리에 포함되어 있는지 확인한다.
df['in_candidates'] = df['category'].apply(is_in_candidates)

In [ ]:
df

,quote,author,category,token length,author_name_only,in_candidates
0,"I'm selfish, impatient and a little insecure. ...",Marilyn Monroe,"best, life, love, mistakes, truth",41,marilyn monroe,1
1,You know you're in love when you can't fall as...,Dr. Seuss,"dreams, love, reality, sleep",18,dr. seuss,1
2,A friend is someone who knows all about you an...,Elbert Hubbard,"friend, friendship, knowledge, love",13,elbert hubbard,1
3,Darkness cannot drive out darkness: only light...,"Martin Luther King Jr., A Testament of Hope: T...","darkness, drive-out, hate, inspirational, light",20,martin luther king jr.,1
4,We accept the love we think we deserve.,"Stephen Chbosky, The Perks of Being a Wallflower","inspirational, love",8,stephen chbosky,1
...,...,...,...,...,...,...
183655,Stephen King in many respects is a wonderful w...,Anne Rice,"reading, people, king",39,anne rice,1
183656,One faces the future with one's past.,Pearl S. Buck,"past, faces",7,pearl s. buck,1
183657,What else does anxiety about the future bring ...,Thomas a Kempis,"anxiety, you, sorrow",13,thomas a kempis,1
183658,The wave of the future is coming and there is ...,Anne Morrow Lindbergh,"fighting, wave, coming",13,anne morrow lindbergh,0
183659,The fact is that all writers create their prec...,Jorge Luis Borges,"work, past, create",26,jorge luis borges,1

In [ ]:
# 상위 150개의 카테고리에 포함되어 있는 데이터만 선택한다.
selected = df[df['in_candidates'] == 1]

In [106]:
selected

,quote,author,category,token length,author_name_only,in_candidates
0,"I'm selfish, impatient and a little insecure. ...",Marilyn Monroe,"best, life, love, mistakes, truth",41,marilyn monroe,1
1,You know you're in love when you can't fall as...,Dr. Seuss,"dreams, love, reality, sleep",18,dr. seuss,1
2,A friend is someone who knows all about you an...,Elbert Hubbard,"friend, friendship, knowledge, love",13,elbert hubbard,1
3,Darkness cannot drive out darkness: only light...,"Martin Luther King Jr., A Testament of Hope: T...","darkness, drive-out, hate, inspirational, light",20,martin luther king jr.,1
4,We accept the love we think we deserve.,"Stephen Chbosky, The Perks of Being a Wallflower","inspirational, love",8,stephen chbosky,1
...,...,...,...,...,...,...
183654,The man who comes up with a means for doing or...,J. Paul Getty,"man, doing, better",28,j. paul getty,1
183655,Stephen King in many respects is a wonderful w...,Anne Rice,"reading, people, king",39,anne rice,1
183656,One faces the future with one's past.,Pearl S. Buck,"past, faces",7,pearl s. buck,1
183657,What else does anxiety about the future bring ...,Thomas a Kempis,"anxiety, you, sorrow",13,thomas a kempis,1
183659,The fact is that all writers create their prec...,Jorge Luis Borges,"work, past, create",26,jorge luis borges,1

In [115]:
# 불필요한 컬럼을 제거한다.
selected = selected.drop(['in_candidates'], axis=1)
selected = selected.drop(['author_name_only'], axis=1)
selected = selected.drop(['token length'], axis=1)

In [116]:
selected

,quote,author,category
0,"I'm selfish, impatient and a little insecure. ...",Marilyn Monroe,"best, life, love, mistakes, truth"
1,You know you're in love when you can't fall as...,Dr. Seuss,"dreams, love, reality, sleep"
2,A friend is someone who knows all about you an...,Elbert Hubbard,"friend, friendship, knowledge, love"
3,Darkness cannot drive out darkness: only light...,"Martin Luther King Jr., A Testament of Hope: T...","darkness, drive-out, hate, inspirational, light"
4,We accept the love we think we deserve.,"Stephen Chbosky, The Perks of Being a Wallflower","inspirational, love"
...,...,...,...
183654,The man who comes up with a means for doing or...,J. Paul Getty,"man, doing, better"
183655,Stephen King in many respects is a wonderful w...,Anne Rice,"reading, people, king"
183656,One faces the future with one's past.,Pearl S. Buck,"past, faces"
183657,What else does anxiety about the future bring ...,Thomas a Kempis,"anxiety, you, sorrow"
183659,The fact is that all writers create their prec...,Jorge Luis Borges,"work, past, create"

In [117]:
selected.to_csv('selected_quotes_119938.csv', index=False)